
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Lenin
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JButton getBtnPersonas() {
        return btnPersonas;
    }

    public void setBtnPersonas(JButton btnPersonas) {
        this.btnPersonas = btnPersonas;
    }

    public JMenuItem getMenuListaPersonas() {
        return menuListaPersonas;
    }

    public void setMenuListaPersonas(JMenuItem menuListaPersonas) {
        this.menuListaPersonas = menuListaPersonas;
    }

    public JMenuItem getMenuPersonascrud() {
        return menuPersonascrud;
    }

    public void setMenuPersonascrud(JMenuItem menuPersonascrud) {
        this.menuPersonascrud = menuPersonascrud;
    }

    public JDesktopPane getDptPrincipal() {
        return dptPrincipal;
    }

    public void setDptPrincipal(JDesktopPane dptPrincipal) {
        this.dptPrincipal = dptPrincipal;
    }

    public JMenu getMnuCrudPersonas() {
        return mnuCrudPersonas;
    }

    public void setMnuCrudPersonas(JMenu mnuCrudPersonas) {
        this.mnuCrudPersonas = mnuCrudPersonas;
    }

    public JButton getBtnVentas() {
        return btnVentas;
    }

    public void setBtnVentas(JButton btnVentas) {
        this.btnVentas = btnVentas;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPersonas = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        dptPrincipal = new javax.swing.JDesktopPane();
        JMenuBar = new javax.swing.JMenuBar();
        mnuCrudPersonas = new javax.swing.JMenu();
        menuPersonascrud = new javax.swing.JMenuItem();
        menuListaPersonas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tienda");

        jToolBar1.setRollover(true);

        btnPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/grupo-de-chat.png"))); // NOI18N
        btnPersonas.setToolTipText("Crear Persona");
        btnPersonas.setFocusable(false);
        btnPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPersonas);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/punto-de-venta.png"))); // NOI18N
        btnVentas.setFocusable(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnVentas);

        javax.swing.GroupLayout dptPrincipalLayout = new javax.swing.GroupLayout(dptPrincipal);
        dptPrincipal.setLayout(dptPrincipalLayout);
        dptPrincipalLayout.setHorizontalGroup(
            dptPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dptPrincipalLayout.setVerticalGroup(
            dptPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        mnuCrudPersonas.setText("Personas");
        mnuCrudPersonas.setToolTipText("Crear Persona");

        menuPersonascrud.setText("Crear Persona");
        mnuCrudPersonas.add(menuPersonascrud);

        menuListaPersonas.setText("Lista Personas");
        mnuCrudPersonas.add(menuListaPersonas);

        JMenuBar.add(mnuCrudPersonas);

        jMenu2.setText("Productos");
        JMenuBar.add(jMenu2);

        jMenu4.setText("Ventas");
        JMenuBar.add(jMenu4);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                    .addComponent(dptPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dptPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JButton btnPersonas;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane dptPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuListaPersonas;
    private javax.swing.JMenuItem menuPersonascrud;
    private javax.swing.JMenu mnuCrudPersonas;
    // End of variables declaration//GEN-END:variables
}
